# Generated by Django 4.2.3 on 2023-11-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateField(help_text='aaaa-mm-dd', verbose_name='Data'),
        ),
    ]
