# Generated by Django 4.2.3 on 2023-12-08 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_petshop_alter_reserva_dia_da_reserva_reserva_petshop'),
    ]

    operations = [
        migrations.CreateModel(
            name='PorteAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porte', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='porte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='base.porteanimal'),
        ),
    ]
