# Generated by Django 4.2.11 on 2024-04-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_porteanimal_reserva_porte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='porteanimal',
            old_name='porte',
            new_name='porte_animal',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='porte',
            new_name='porte_animal',
        ),
    ]
