# Generated by Django 4.2.11 on 2024-04-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_porte_porteanimal_porte_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='porteanimal',
            name='porte_animal',
            field=models.CharField(choices=[(1, 'Pequeno'), (2, 'Médio'), (3, 'Grande')], max_length=50),
        ),
    ]
